#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

( cd airfoil_f && ./Allrun )

( cd airfoil_b && ./Allrun )

( cd all && ./Allrun )

#------------------------------------------------------------------------------
