#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
#runApplication topoSet
#cleanCase0
#runApplication blockMesh
transformPoints -translate "(-1 0 0)" > /dev/null
transformPoints -rotate-angle "((0 1 0) AOA)" > /dev/null
transformPoints -translate "(1 0 0)" > /dev/null
transformPoints -translate "(0 0 h_c)" > /dev/null
transformPoints -scale Resize > /dev/null
#---------------------------------------------------------------------
