#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

./Allclean

cp -r 0.komega 0
runApplication blockMesh
mergeMeshes . ../airfoil -overwrite > /dev/null

runApplication checkMesh

# Use cellSets to write zoneID
runApplication setFields
qsub run.pbs
# ./run
# Serial
#runApplication $(getApplication)

# Parallel
#runApplication decomposePar 
#runParallel $(getApplication)

#------------------------------------------------------------------------------
