#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
#runApplication topoSet
cleanCase0
cp -r 0.komega 0
runApplication blockMesh
transformPoints -translate "(-1.0 0 0)" > /dev/null
transformPoints -rotate-angle "((0.0 1 0) AOA)" > /dev/null
transformPoints -translate "(1.0 0 0)" > /dev/null

qsub run.pbs

#decomposePar -force > log.dec 2>&1
#mpirun -np 24 simpleFoam -parallel  > log.sol 2>&1
#reconstructPar -latestTime
#rm -r processor*
#postProcess -func 'pWall' -fields '(p U)' -latestTime
#grep -oP '(?<=ClockTime\s=\s)\S+' log.sol > clockTime.dat 2>&1
#grep -oP '(?<=ExecutionTime\s=\s)\S+' log.sol > exeTime.dat 2>&1
#rm -r dynamicCode
#---------------------------------------------------------------------
